stages:
  - deploy

deploy:
  image: ruby:2.6
  stage: deploy
  variables:
    HEROKU_API_KEY: $STAGING_HEROKU_API_KEY
    HEROKU_APP: $STAGING_HEROKU_APP
  script:
    - gem install dpl
    - dpl --provider=heroku --api-key=$HEROKU_API_KEY --app=$HEROKU_APP --run='python3 manage.py migrate'
  only:
    - master